<a href="https://colab.research.google.com/github/Navadeep-06/Assignments/blob/main/lec_21_encoding_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import pandas as pd

data = {
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female'],
    'City': ['Mumbai', 'Delhi', 'Chennai', 'Mumbai', 'Delhi'],
    'Size': ['Small', 'Large', 'Medium', 'Large', 'Small'],
    'Age': [25, 45, 32, 60, 28],
    'Fare': [15, 300, 85, 450, 20]
}

df = pd.DataFrame(data)
print(df)

   Gender     City    Size  Age  Fare
0    Male   Mumbai   Small   25    15
1  Female    Delhi   Large   45   300
2  Female  Chennai  Medium   32    85
3    Male   Mumbai   Large   60   450
4  Female    Delhi   Small   28    20

In [31]:
from sklearn.preprocessing import LabelEncoder #with encoder

# Initialize LabelEncoder
le=LabelEncoder()

# Apply Label Encoding to the 'Gender' column by creating a new gender_encoded column
df["Gender"]=le.fit_transform(df["Gender"])

# Display the updated DataFrame
print(df)

   Gender     City    Size  Age  Fare
0       1   Mumbai   Small   25    15
1       0    Delhi   Large   45   300
2       0  Chennai  Medium   32    85
3       1   Mumbai   Large   60   450
4       0    Delhi   Small   28    20

In [32]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False) # sparse_output=False makes it return a dense array directly

# Fit and transform the 'City' column
# ohe expects a 2D array-like input, df[['City']] is a DataFrame (2D)
encoded_cities_array = ohe.fit_transform(df[['City']])

# Get feature names for the new columns
feature_names = ohe.get_feature_names_out(['City'])

# Create a DataFrame from the encoded data
encoded_df = pd.DataFrame(encoded_cities_array, columns=feature_names, index=df.index)

# Concatenate the original DataFrame (without 'City') with the new encoded DataFrame
df = pd.concat([df.drop('City', axis=1), encoded_df], axis=1)

df

   Gender    Size  Age  Fare  City_Chennai  City_Delhi  City_Mumbai
0       1   Small   25    15           0.0         0.0          1.0
1       0   Large   45   300           0.0         1.0          0.0
2       0  Medium   32    85           1.0         0.0          0.0
3       1   Large   60   450           0.0         0.0          1.0
4       0   Small   28    20           0.0         1.0          0.0

In [33]:
df['Size']=le.fit_transform(df['Size'])
df

   Gender  Size  Age  Fare  City_Chennai  City_Delhi  City_Mumbai
0       1     2   25    15           0.0         0.0          1.0
1       0     0   45   300           0.0         1.0          0.0
2       0     1   32    85           1.0         0.0          0.0
3       1     0   60   450           0.0         0.0          1.0
4       0     2   28    20           0.0         1.0          0.0

USING INBUILD DATAFRAME USING TO ENCODE

In [28]:
import pandas as pd

# Re-create df1 from the original data to ensure 'City' column exists
data = {
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female'],
    'City': ['Mumbai', 'Delhi', 'Chennai', 'Mumbai', 'Delhi'],
    'Size': ['Small', 'Large', 'Medium', 'Large', 'Small'],
    'Age': [25, 45, 32, 60, 28],
    'Fare': [15, 300, 85, 450, 20]
}
df1 = pd.DataFrame(data)

# Re-apply Gender mapping (as done in f57ZDftwtWDm)
df1['Gender']=df1['Gender'].map({'Male':'0','Female':'1'})

# Re-apply Size mapping (as done in ykJUWHsmwAWu, converting to int for consistency)
df1['Size']=df1['Size'].map({'Small':0,'Medium':1,'Large':2})

# Now apply one-hot encoding to 'City'
df1 = pd.get_dummies(df1, columns=['City'], drop_first=True)

# Print the transformed df1
print(df1)

  Gender  Size  Age  Fare  City_Delhi  City_Mumbai
0      0     0   25    15       False         True
1      1     2   45   300        True        False
2      1     1   32    85       False        False
3      0     2   60   450       False         True
4      1     0   28    20        True        False